// Generated by scripts/build-goals-seed.mjs. Do not edit by hand.
// Popular goals used when the goals search RPC is unavailable (offline, or before migration).
export interface CatalogueGoal { id: string; label: string; category: string; keywords: string }

export const GOAL_FALLBACK: CatalogueGoal[] = [
  {
    "id": "get-fit-and-strong",
    "label": "Get fit and strong",
    "category": "Health & Fitness",
    "keywords": "fitness, strength, gym, in shape"
  },
  {
    "id": "run-a-marathon",
    "label": "Run a marathon",
    "category": "Running & Endurance",
    "keywords": "marathon, 42k, 26.2, running"
  },
  {
    "id": "build-a-calmer-routine",
    "label": "Build a calmer routine",
    "category": "Mental Wellbeing",
    "keywords": "calm, routine, slow living, balance"
  },
  {
    "id": "climb-kilimanjaro",
    "label": "Climb Kilimanjaro",
    "category": "Adventure & Outdoors",
    "keywords": "kilimanjaro, mountain, africa, summit"
  },
  {
    "id": "pass-my-driving-test",
    "label": "Pass my driving test",
    "category": "Driving & Transport",
    "keywords": "driving test, driving licence, learner, practical test"
  },
  {
    "id": "pass-an-exam",
    "label": "Pass an exam",
    "category": "Exams & Qualifications",
    "keywords": "exam, test, study, revision"
  },
  {
    "id": "learn-conversational-spanish",
    "label": "Learn conversational Spanish",
    "category": "Languages",
    "keywords": "spanish, espanol, language, conversation"
  },
  {
    "id": "write-a-book",
    "label": "Write a book",
    "category": "Creative Arts & Writing",
    "keywords": "book, novel, author, writing"
  },
  {
    "id": "get-promoted",
    "label": "Get promoted",
    "category": "Career Growth",
    "keywords": "promotion, career, raise, next level"
  },
  {
    "id": "start-a-side-business",
    "label": "Start a side business",
    "category": "Business & Entrepreneurship",
    "keywords": "side business, side hustle, extra income, evenings"
  },
  {
    "id": "save-for-a-home-deposit",
    "label": "Save for a home deposit",
    "category": "Money & Saving",
    "keywords": "house deposit, saving, mortgage, first home"
  },
  {
    "id": "speak-confidently-in-public",
    "label": "Speak confidently in public",
    "category": "Confidence & Communication",
    "keywords": "public speaking, presentations, confidence, nerves"
  },
  {
    "id": "start-going-to-the-gym",
    "label": "Start going to the gym",
    "category": "Health & Fitness",
    "keywords": "gym, workout, weights, beginner"
  },
  {
    "id": "do-my-first-pull-up",
    "label": "Do my first pull-up",
    "category": "Health & Fitness",
    "keywords": "pull up, chin up, upper body, calisthenics"
  },
  {
    "id": "run-my-first-5k",
    "label": "Run my first 5k",
    "category": "Running & Endurance",
    "keywords": "5k, couch to 5k, running, beginner"
  },
  {
    "id": "run-a-10k",
    "label": "Run a 10k",
    "category": "Running & Endurance",
    "keywords": "10k, running, race, distance"
  },
  {
    "id": "lose-weight",
    "label": "Lose weight",
    "category": "Weight & Nutrition",
    "keywords": "weight loss, fat loss, slim down, diet"
  },
  {
    "id": "lose-10-kilos",
    "label": "Lose 10 kilos",
    "category": "Weight & Nutrition",
    "keywords": "weight loss, 10kg, fat loss, diet"
  },
  {
    "id": "lose-weight-after-40",
    "label": "Lose weight after 40",
    "category": "Weight & Nutrition",
    "keywords": "weight loss, midlife, metabolism, diet"
  },
  {
    "id": "manage-my-anxiety",
    "label": "Manage my anxiety",
    "category": "Mental Wellbeing",
    "keywords": "anxiety, worry, panic, mental health"
  },
  {
    "id": "feel-less-stressed",
    "label": "Feel less stressed",
    "category": "Mental Wellbeing",
    "keywords": "stress, overwhelm, pressure, calm"
  },
  {
    "id": "recover-from-burnout",
    "label": "Recover from burnout",
    "category": "Mental Wellbeing",
    "keywords": "burnout, exhaustion, recovery, work stress"
  },
  {
    "id": "sleep-better",
    "label": "Sleep better",
    "category": "Sleep & Energy",
    "keywords": "sleep, insomnia, rest, tired"
  },
  {
    "id": "get-eight-hours-of-sleep-a-night",
    "label": "Get eight hours of sleep a night",
    "category": "Sleep & Energy",
    "keywords": "sleep, eight hours, rest, bedtime"
  },
  {
    "id": "fix-my-sleep-schedule",
    "label": "Fix my sleep schedule",
    "category": "Sleep & Energy",
    "keywords": "sleep schedule, body clock, bedtime, routine"
  },
  {
    "id": "quit-smoking",
    "label": "Quit smoking",
    "category": "Quitting & Cutting Down",
    "keywords": "smoking, cigarettes, stop smoking, nicotine"
  },
  {
    "id": "stop-vaping",
    "label": "Stop vaping",
    "category": "Quitting & Cutting Down",
    "keywords": "vaping, vape, nicotine, e cigarette"
  },
  {
    "id": "cut-down-on-alcohol",
    "label": "Cut down on alcohol",
    "category": "Quitting & Cutting Down",
    "keywords": "alcohol, drinking, units, sober curious"
  },
  {
    "id": "climb-a-mountain",
    "label": "Climb a mountain",
    "category": "Adventure & Outdoors",
    "keywords": "mountain, summit, hiking, peak"
  },
  {
    "id": "reach-everest-base-camp",
    "label": "Reach Everest Base Camp",
    "category": "Adventure & Outdoors",
    "keywords": "everest, base camp, nepal, trek"
  },
  {
    "id": "travel-solo-for-the-first-time",
    "label": "Travel solo for the first time",
    "category": "Travel",
    "keywords": "solo travel, alone, trip, independence"
  },
  {
    "id": "visit-every-continent",
    "label": "Visit every continent",
    "category": "Travel",
    "keywords": "continents, world travel, bucket list, adventure"
  },
  {
    "id": "take-a-gap-year",
    "label": "Take a gap year",
    "category": "Travel",
    "keywords": "gap year, travel, career break, sabbatical"
  },
  {
    "id": "pass-my-driving-theory-test",
    "label": "Pass my driving theory test",
    "category": "Driving & Transport",
    "keywords": "theory test, hazard perception, highway code, learner"
  },
  {
    "id": "learn-to-drive",
    "label": "Learn to drive",
    "category": "Driving & Transport",
    "keywords": "driving lessons, learner driver, car, licence"
  },
  {
    "id": "learn-to-play-tennis",
    "label": "Learn to play tennis",
    "category": "Sport & Active Hobbies",
    "keywords": "tennis, racket, court, lessons"
  },
  {
    "id": "join-a-football-team",
    "label": "Join a football team",
    "category": "Sport & Active Hobbies",
    "keywords": "football, soccer, team, sunday league"
  },
  {
    "id": "get-better-at-golf",
    "label": "Get better at golf",
    "category": "Sport & Active Hobbies",
    "keywords": "golf, handicap, swing, course"
  },
  {
    "id": "start-a-vegetable-garden",
    "label": "Start a vegetable garden",
    "category": "Nature, Animals & Garden",
    "keywords": "vegetables, grow your own, garden, allotment"
  },
  {
    "id": "get-an-allotment",
    "label": "Get an allotment",
    "category": "Nature, Animals & Garden",
    "keywords": "allotment, community garden, growing, plot"
  },
  {
    "id": "grow-my-own-herbs",
    "label": "Grow my own herbs",
    "category": "Nature, Animals & Garden",
    "keywords": "herbs, windowsill, growing, kitchen"
  },
  {
    "id": "pass-my-school-exams",
    "label": "Pass my school exams",
    "category": "Exams & Qualifications",
    "keywords": "school exams, gcse, a levels, high school"
  },
  {
    "id": "get-into-university",
    "label": "Get into university",
    "category": "Exams & Qualifications",
    "keywords": "university, college, admissions, application"
  },
  {
    "id": "learn-french",
    "label": "Learn French",
    "category": "Languages",
    "keywords": "french, francais, language, fluent"
  },
  {
    "id": "learn-german",
    "label": "Learn German",
    "category": "Languages",
    "keywords": "german, deutsch, language, grammar"
  },
  {
    "id": "build-a-study-routine",
    "label": "Build a study routine",
    "category": "Learning & Study Skills",
    "keywords": "study routine, revision, schedule, habit"
  },
  {
    "id": "improve-my-memory",
    "label": "Improve my memory",
    "category": "Learning & Study Skills",
    "keywords": "memory, recall, memorise, brain"
  },
  {
    "id": "read-20-books-this-year",
    "label": "Read 20 books this year",
    "category": "Learning & Study Skills",
    "keywords": "reading, books, reading challenge, habit"
  },
  {
    "id": "learn-to-code",
    "label": "Learn to code",
    "category": "Tech & Digital Skills",
    "keywords": "coding, programming, developer, beginner"
  },
  {
    "id": "learn-python",
    "label": "Learn Python",
    "category": "Tech & Digital Skills",
    "keywords": "python, programming, coding, scripts"
  },
  {
    "id": "learn-javascript",
    "label": "Learn JavaScript",
    "category": "Tech & Digital Skills",
    "keywords": "javascript, web development, coding, frontend"
  },
  {
    "id": "finish-my-novel",
    "label": "Finish my novel",
    "category": "Creative Arts & Writing",
    "keywords": "novel, first draft, fiction, writing"
  },
  {
    "id": "write-every-day",
    "label": "Write every day",
    "category": "Creative Arts & Writing",
    "keywords": "daily writing, habit, journal, words"
  },
  {
    "id": "get-a-pay-rise",
    "label": "Get a pay rise",
    "category": "Career Growth",
    "keywords": "pay rise, raise, salary, negotiation"
  },
  {
    "id": "negotiate-a-higher-salary",
    "label": "Negotiate a higher salary",
    "category": "Career Growth",
    "keywords": "salary negotiation, pay, offer, raise"
  },
  {
    "id": "find-a-new-job",
    "label": "Find a new job",
    "category": "Job Search",
    "keywords": "job search, new job, hiring, applications"
  },
  {
    "id": "get-my-first-job",
    "label": "Get my first job",
    "category": "Job Search",
    "keywords": "first job, graduate, entry level, school leaver"
  },
  {
    "id": "get-a-graduate-job",
    "label": "Get a graduate job",
    "category": "Job Search",
    "keywords": "graduate scheme, grad job, entry level, university"
  },
  {
    "id": "become-a-manager",
    "label": "Become a manager",
    "category": "Leadership & Management",
    "keywords": "first time manager, management, promotion, leadership"
  },
  {
    "id": "be-a-better-manager",
    "label": "Be a better manager",
    "category": "Leadership & Management",
    "keywords": "management, leading people, team, skills"
  },
  {
    "id": "lead-my-team-through-change",
    "label": "Lead my team through change",
    "category": "Leadership & Management",
    "keywords": "change management, transformation, team, leadership"
  },
  {
    "id": "start-a-business",
    "label": "Start a business",
    "category": "Business & Entrepreneurship",
    "keywords": "start a business, startup, founder, entrepreneur"
  },
  {
    "id": "validate-my-business-idea",
    "label": "Validate my business idea",
    "category": "Business & Entrepreneurship",
    "keywords": "validation, customer interviews, idea, market"
  },
  {
    "id": "go-freelance",
    "label": "Go freelance",
    "category": "Freelancing & Side Income",
    "keywords": "freelance, self employed, independent, contractor"
  },
  {
    "id": "get-my-first-freelance-client",
    "label": "Get my first freelance client",
    "category": "Freelancing & Side Income",
    "keywords": "freelance client, first client, gigs, proposals"
  },
  {
    "id": "earn-extra-income-on-the-side",
    "label": "Earn extra income on the side",
    "category": "Freelancing & Side Income",
    "keywords": "side income, extra money, side hustle, earnings"
  },
  {
    "id": "build-an-emergency-fund",
    "label": "Build an emergency fund",
    "category": "Money & Saving",
    "keywords": "emergency fund, savings, rainy day, safety net"
  },
  {
    "id": "get-out-of-debt",
    "label": "Get out of debt",
    "category": "Money & Saving",
    "keywords": "debt, pay off, credit cards, loans"
  },
  {
    "id": "start-investing",
    "label": "Start investing",
    "category": "Investing & Financial Planning",
    "keywords": "investing, stocks, index funds, beginner"
  },
  {
    "id": "invest-in-index-funds",
    "label": "Invest in index funds",
    "category": "Investing & Financial Planning",
    "keywords": "index funds, etfs, passive investing, diversification"
  },
  {
    "id": "open-a-tax-free-savings-or-investment-account",
    "label": "Open a tax-free savings or investment account",
    "category": "Investing & Financial Planning",
    "keywords": "tax free account, isa, roth ira, tfsa"
  },
  {
    "id": "move-out-of-my-parents-home",
    "label": "Move out of my parents' home",
    "category": "Home & Housing",
    "keywords": "moving out, independence, renting, first flat"
  },
  {
    "id": "find-a-flat-to-rent",
    "label": "Find a flat to rent",
    "category": "Home & Housing",
    "keywords": "renting, flat hunting, lettings, tenancy"
  },
  {
    "id": "find-a-flatmate",
    "label": "Find a flatmate",
    "category": "Home & Housing",
    "keywords": "flatmate, house share, roommate, renting"
  },
  {
    "id": "move-abroad",
    "label": "Move abroad",
    "category": "Moving & Relocation",
    "keywords": "move abroad, emigrate, relocation, expat"
  },
  {
    "id": "get-a-work-visa",
    "label": "Get a work visa",
    "category": "Moving & Relocation",
    "keywords": "work visa, sponsorship, immigration, permit"
  },
  {
    "id": "get-permanent-residency",
    "label": "Get permanent residency",
    "category": "Moving & Relocation",
    "keywords": "permanent residency, green card, settlement, immigration"
  },
  {
    "id": "be-a-more-patient-parent",
    "label": "Be a more patient parent",
    "category": "Family & Parenting",
    "keywords": "patient parenting, calm, kids, temper"
  },
  {
    "id": "spend-more-quality-time-with-my-kids",
    "label": "Spend more quality time with my kids",
    "category": "Family & Parenting",
    "keywords": "quality time, family, children, connection"
  },
  {
    "id": "get-my-baby-sleeping-through-the-night",
    "label": "Get my baby sleeping through the night",
    "category": "Family & Parenting",
    "keywords": "baby sleep, sleep training, night waking, infant"
  },
  {
    "id": "make-new-friends",
    "label": "Make new friends",
    "category": "Relationships & Social Life",
    "keywords": "friends, friendship, social, meet people"
  },
  {
    "id": "make-friends-as-an-adult",
    "label": "Make friends as an adult",
    "category": "Relationships & Social Life",
    "keywords": "adult friendships, social life, connection, loneliness"
  },
  {
    "id": "find-a-partner",
    "label": "Find a partner",
    "category": "Relationships & Social Life",
    "keywords": "dating, relationship, partner, love"
  },
  {
    "id": "give-a-great-presentation-at-work",
    "label": "Give a great presentation at work",
    "category": "Confidence & Communication",
    "keywords": "presentation, slides, delivery, work"
  },
  {
    "id": "give-a-wedding-speech",
    "label": "Give a wedding speech",
    "category": "Confidence & Communication",
    "keywords": "wedding speech, best man, maid of honour, toast"
  },
  {
    "id": "build-a-morning-routine",
    "label": "Build a morning routine",
    "category": "Habits & Productivity",
    "keywords": "morning routine, habits, start the day, productivity"
  },
  {
    "id": "get-more-done-each-day",
    "label": "Get more done each day",
    "category": "Habits & Productivity",
    "keywords": "productivity, focus, output, efficiency"
  },
  {
    "id": "manage-my-time-better",
    "label": "Manage my time better",
    "category": "Habits & Productivity",
    "keywords": "time management, schedule, priorities, calendar"
  },
  {
    "id": "learn-the-guitar",
    "label": "Learn the guitar",
    "category": "Music & Performance",
    "keywords": "guitar, chords, strumming, music"
  },
  {
    "id": "learn-the-piano",
    "label": "Learn the piano",
    "category": "Music & Performance",
    "keywords": "piano, keyboard, lessons, music"
  },
  {
    "id": "learn-to-sing",
    "label": "Learn to sing",
    "category": "Music & Performance",
    "keywords": "singing, voice, lessons, vocals"
  },
  {
    "id": "learn-to-cook",
    "label": "Learn to cook",
    "category": "Cooking & Food",
    "keywords": "cooking, beginner, recipes, kitchen"
  },
  {
    "id": "cook-from-scratch-every-day",
    "label": "Cook from scratch every day",
    "category": "Cooking & Food",
    "keywords": "home cooking, from scratch, meals, habit"
  },
  {
    "id": "master-10-go-to-recipes",
    "label": "Master 10 go-to recipes",
    "category": "Cooking & Food",
    "keywords": "recipes, repertoire, cooking, meals"
  },
  {
    "id": "volunteer-regularly",
    "label": "Volunteer regularly",
    "category": "Community & Giving Back",
    "keywords": "volunteering, charity, community, giving back"
  },
  {
    "id": "find-a-cause-i-care-about",
    "label": "Find a cause I care about",
    "category": "Community & Giving Back",
    "keywords": "cause, charity, purpose, impact"
  },
  {
    "id": "raise-money-for-charity",
    "label": "Raise money for charity",
    "category": "Community & Giving Back",
    "keywords": "fundraising, charity, sponsorship, challenge"
  },
  {
    "id": "get-on-top-of-life-admin",
    "label": "Get on top of life admin",
    "category": "Life Admin & Organisation",
    "keywords": "life admin, paperwork, bills, organisation"
  },
  {
    "id": "sort-out-my-taxes",
    "label": "Sort out my taxes",
    "category": "Life Admin & Organisation",
    "keywords": "tax return, taxes, filing, admin"
  },
  {
    "id": "file-my-tax-return-on-time",
    "label": "File my tax return on time",
    "category": "Life Admin & Organisation",
    "keywords": "tax return, deadline, self assessment, filing"
  },
  {
    "id": "find-my-purpose",
    "label": "Find my purpose",
    "category": "Personal Growth & Purpose",
    "keywords": "purpose, meaning, direction, fulfilment"
  },
  {
    "id": "work-out-what-i-want-from-life",
    "label": "Work out what I want from life",
    "category": "Personal Growth & Purpose",
    "keywords": "life direction, values, clarity, goals"
  },
  {
    "id": "become-the-best-version-of-myself",
    "label": "Become the best version of myself",
    "category": "Personal Growth & Purpose",
    "keywords": "self improvement, growth, potential, better"
  }
];
